services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - /home/debian/HelperBot/data:/app/Discord/data
      - /media/archive/Discord/archives:/app/Discord/data/archives
      - /etc/localtime:/etc/localtime
    restart: always
    logging:
      driver: "json-file"
    environment:
      - PYTHONUNBUFFERED=1
